project:
  type: book
  output-dir: book

execute: 
  freeze: auto

book:
  title: "Fitted Q-Iteration: Estimación de niveles de presas"
  author: "Erika Rubí Jiménez Guzmán"
  language: es
  date: "28/04/2026"
  image: Imagenes\fcfm.png
  favicon: Imagenes\fcfm.png
  downloads: [pdf, epub]

  sidebar:
    logo: Imagenes\logos.jpeg
    style: floating
    collapse-level: 2
    border: true
    search: true

  repo-url: https://github.com/RubiJimenez929/Tesis-Licenciatura
  page-navigation: true 

  chapters:
    - index.qmd
    - intro.qmd

    - part: "Preliminares"
      chapters:
        - Inteligencia artificial.qmd
        - Q-Learning.qmd
      
    - part: "Caso de estudio"
      chapters:
        - Caso_estudio.qmd


    - conclusiones.qmd
    - futuros_trabajos.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    highlight-style: a11y
    toc: true
    toc-location: right
    code-fold: true
    code-copy: true

  pdf:
    documentclass: scrreprt
    papersize: letter
    toc: true
    number-sections: true
    pdf-engine: lualatex

  epub:
    cover-image: Imagenes\fcfm.png